version: '3.8'

services:
  app:
    image: "guilhermercarvalho/restfull-students-app:v1.0.prod"
    container_name: restfull-students-app-prod
    build:
      context: .
      dockerfile: docker/dockerfiles/app.Dockerfile
    depends_on:
      - cache-redis

  cache-redis:
    container_name: restfull-students-cache-redis-prod
    image: "redis:7.0.4-alpine3.16"
    restart: unless-stopped

  load-balancer:
    image: "guilhermercarvalho/restfull-students-load-balancer:v1.0.prod"
    container_name: restfull-students-load-balancer-prod
    build:
      context: .
      dockerfile: docker/dockerfiles/nginx.Dockerfile
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
