version: '3.8'

services:
  app:
    image: "guilhermercarvalho/restfull-students-app:v1.0.dev"
    container_name: restfull-students-app
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
      args:
        # Update 'VARIANT' to pick an LTS version of Node.js: 16, 14, 12.
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 16-bullseye

    volumes:
      - ..:/workspace:cached

    env_file:
      - "./env/app.env"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db-postgres
    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      - db-postgres
      - db-mysql

  db-postgres:
    container_name: restfull-students-db-postgres
    image: "guilhermercarvalho/restfull-students-db-psql14:v1.0.dev"
    build:
      context: .
      dockerfile: dockerfiles/db-postgres.Dockerfile
    restart: unless-stopped
    env_file:
      - "./env/db-postgres.env"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db-mysql:
    container_name: restfull-students-db-mysql
    image: "guilhermercarvalho/restfull-students-db-mysql5:v1.0.dev"
    build:
      context: .
      dockerfile: dockerfiles/db-mysql.Dockerfile
    restart: unless-stopped
    env_file:
      - "./env/db-mysql.env"
