version: '3.8'

services:
  app:
    image: "guilhermercarvalho/restfull-students-app:v1.0.dev"
    container_name: restfull-students-app
    build:
      context: .
      dockerfile: dockerfiles/app.Dockerfile
      args:
        VARIANT: 0.204.9-16-bullseye
    volumes:
      - ..:/workspace:cached
    env_file:
      - "./env/app.env"
    command: sleep infinity
    depends_on:
      - db-postgres
      - db-mysql
      - cache-redis

  db-postgres:
    container_name: restfull-students-db-postgres
    image: postgres:14-alpine3.14
    restart: unless-stopped
    env_file:
      - "./env/db-postgres.env"

  db-mysql:
    container_name: restfull-students-db-mysql
    image: mysql:5.7.38
    restart: unless-stopped
    env_file:
      - "./env/db-mysql.env"

  cache-redis:
    container_name: restfull-students-cache-redis
    image: "redis:7.0.4-alpine3.16"
    restart: unless-stopped
    depends_on:
      - db-postgres
      - db-mysql
