name: Node.js CI

on:
  push:
    paths-ignore:
      - 'src/**'
      - 'test/**'
      - 'sqlite/**'
  pull_request:
    paths-ignore:
      - 'src/**'
      - 'test/**'
      - 'sqlite/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
